Testando o jupyter notebook

In [11]:
a = 2
print(a)

2

Ler o arquivo csv e Primeiras Linhas

In [12]:
import pandas as pd

df = pd.read_csv('dados.csv')

display(df.head())

   id   nome  idade          cidade  salario
0   1    Ana     25       Sao Paulo     5000
1   2  Bruno     30  Rio de Janeiro     6200
2   3  Carla     22        Curitiba     4800
3   4  Diego     35  Belo Horizonte     7100
4   5  Elena     28        Salvador     5500

Descrição das colunas:
 
df.describe() calcula automaticamente a média, valor mínimo e máximo das colunas numéricas(idade e salário)

In [13]:
display(df.describe().round(2))

         id  idade  salario
count  5.00   5.00     5.00
mean   3.00  28.00  5720.00
std    1.58   4.95   941.81
min    1.00  22.00  4800.00
25%    2.00  25.00  5000.00
50%    3.00  28.00  5500.00
75%    4.00  30.00  6200.00
max    5.00  35.00  7100.00

count: quantidade de linhas(pessoas cadastradas)
mean: média dos valores(28 é a idade média)
std: variação(as idades variam cerca de 5 anos em relação a média)
min: menor valor (a pessoa mais nova tem 22)
max: maior valor (a pessoa mais velha tem 35)
50%: valor que está no meio da lista (metade das pessoas tem menos de 28, metade tem mais)

Informações do dataset:

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       5 non-null      int64
 1   nome     5 non-null      object
 2   idade    5 non-null      int64
 3   cidade   5 non-null      object
 4   salario  5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 328.0+ bytes

RangeIndex: 5 linhas(registros)
Data columns: 5 colunas(id, nome, idade, cidade, salario)
Non-null Count: todas as 5 linhas têm dados
Dtype: tipo de dado (int 64: inteiro, object: texto(nome, cidade))